import{a as u,S as p,i as c}from"./assets/vendor-dNBuWDsd.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&r(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();function g(o){const r="https://pixabay.com"+"/api/",e={key:"55027446-560ad86223e1945ccd495c8f6",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0};return u.get(r,{params:e}).then(t=>t.data).catch(t=>{console.log(t)})}const y=new p(".gallery a",{captionDelay:250,captionsData:"alt"}),h=document.querySelector(".gallery"),l=document.querySelector(".loader");function L(o){const s=o.map(a=>{const{webformatURL:r,largeImageURL:e,tags:t,likes:i,views:f,comments:d,downloads:m}=a;return`<li class="item">
        <a class="img-photo" href="${e}"><img src="${r}" alt="${t}"></a>
        <div class="wrap-info">
            <p class="info">Likes ${i}</p>
            <p class="info">Views ${f}</p>
            <p class="info">Comments ${d}</p>
            <p class="info">Downloads ${m}</p>
        </div>
      </li>`}).join("");h.innerHTML=s,y.refresh()}function b(){l.classList.add("loader"),l.style.display="flex"}function w(){l.classList.add("is-hidden")}const n={formEl:document.querySelector(".form"),galleryList:document.querySelector(".gallery")};n.formEl.addEventListener("submit",o=>{o.preventDefault(),n.galleryList.innerHTML="";const a=new FormData(o.target).get("search-text");a.trim()===""?c.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"}):(b(),g(a).then(r=>{r.hits.length===0?c.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"}):L(r.hits)}).catch(r=>{console.log(r)}).finally(()=>w())),n.formEl.reset()});
//# sourceMappingURL=index.js.map
