import{a as g,S as y,i as n}from"./assets/vendor-dNBuWDsd.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&t(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function t(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();function h(o){const t="https://pixabay.com"+"/api/",e={key:"55027446-560ad86223e1945ccd495c8f6",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0};return g.get(t,{params:e}).then(r=>r.data).catch(r=>{console.log(r)})}const p=new y(".gallery a",{captionDelay:250,captionsData:"alt"}),l=document.querySelector(".gallery"),m=document.querySelector(".loader");function L(o){const s=o.map(a=>{const{webformatURL:t,largeImageURL:e,tags:r,likes:i,views:u,comments:f,downloads:d}=a;return`<li class="item">
        <a class="img-photo" href="${e}"><img src="${t}" alt="${r}"></a>
        <div class="wrap-info">
            <p class="info">Likes ${i}</p>
            <p class="info">Views ${u}</p>
            <p class="info">Comments ${f}</p>
            <p class="info">Downloads ${d}</p>
        </div>
      </li>`}).join("");l.innerHTML=s,p.refresh()}function b(){l.innerHTML=""}function w(){m.classList.remove("is-hidden")}function S(){m.classList.add("is-hidden")}const c={formEl:document.querySelector(".form"),galleryList:document.querySelector(".gallery")};c.formEl.addEventListener("submit",o=>{o.preventDefault();const a=new FormData(o.target).get("search-text");a.trim()===""?n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"}):(b(),w(),h(a).then(t=>{t.hits.length===0?n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"}):L(t.hits)}).catch(t=>{console.log(t),n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"})}).finally(()=>S())),c.formEl.reset()});
//# sourceMappingURL=index.js.map
